version: "3.9"
services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432"
    healthcheck:
      test: pg_isready -U root -d simple_bank
      interval: 10s
      timeout: 10s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command:
      ["-path", "/migrations", "-database", "postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable", "up"]
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
  api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
      depends_on:
        - migrate
